Clean up and add configurability
cronitorio/cronitor-ruby pull request #22
Opened 2022-02-18 22:29 UTC by kevintom

* remove api key support from yaml config
* it's not a good practice to encourage storage of credentials in a config file that will likely end up in version control
* use safe navigation operator on logging calls
* allow the user to config the network timeout
* bump version to 4.1.3
* update README documentation to reflect configuration option

2022-02-18 23:33 UTC, aflanagan commented
Great updates!

2022-02-24 21:01 UTC, jeffbyrnes requested changes
Overall, these are great changes! Thanks for providing them.

I’ve left some comments re: the sensitive credentials changes. Curious as to your & others’ thoughts.

2022-02-25 15:45 UTC, aflanagan commented on lib/cronitor.rb
> -
Hey @jeffbyrnes, thanks for still taking the time to review all these PRs and give feedback. It is sooooo appreciated!

In this case I had actually asked @kevintom to remove that. We ended up not supporting it in the other SDKs, and I figured it was easier to align them to all have the same expectations. 

That said, the original intent was to provide an alternative mechanism to env vars for injecting credentials, and so it's nice to see that other people also like the config file approach over env vars. So, with that said, I'm totally OK with us keeping it in there, though to the best of my knowledge it is not currently used by anyone.

2022-02-25 19:02 UTC, jeffbyrnes commented on lib/cronitor.rb
> -
@aflanagan makes sense to be consistent! I’ll defer to that decision. We used the config file mechanism at @evertrue, but this was some years ago, and I haven’t worked there in a long time.

2022-04-05 01:21 UTC, kevintom commented on lib/cronitor/version.rb
> +  VERSION = '4.1.3'
dropped the version bump and cleaned up my commit history to remove that commit.

2022-04-06 17:51 UTC, aflanagan commented on README.md
> +Cronitor.timeout = 20 # defaults to 10 can also be set with ENV['CRONITOR_TIMEOUT']
So nice to have these!

2022-05-02 21:45 UTC, merged